### ISSUE TITLE
Building with haxe

### ISSUE THREAD

**Issue by ThuGie** [Earthquake-Project/EarthQuake-Haxe#1]
Never used haxe before, just downloaded and installed it.
Seems to be a commandline utility, any guide on how to ?

**Comment by Brian151** [comment]
Install FlashDevelop as well
I perhaps should mention that
Then you can open the .hxproj file as a project in flashdevelop

Perhaps I should've clarified that in the first place.
Kinda odd to bring it up, now, though, this has been the source format of my parsing library for a while, now

Tell me if any other confusions

**Comment by ThuGie** [comment]
Building ShockwaveParser
Running Pre-Build Command Line...
cmd: haxe modules.hxml .hxml
Error: Could not process argument .hxml (file not found)
empty part
Build halted with errors.
Done(1)

**Comment by Brian151** [comment]
![image](https://user-images.githubusercontent.com/10995730/29433210-71aea04a-835b-11e7-8c56-0d00c805bc54.png)

You type one of
"RIFF"
"Earthquake"
"Application"

into that box
I really should work on that a bit... /:
sry

**Comment by ThuGie** [comment]
No no problem, at least you are explaining it properly, later on you could write a readme file for github.

**Comment by Brian151** [comment]
yeah, i suppose... lol

**Comment by Brian151** [comment]
https://github.com/Earthquake-Project/EarthQuake-Haxe/commit/4a849399fc55a5a62ece0d02024b5f36031c0e8b
