### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by Mohamed-moneim-said** [Earthquake-Project/EarthQuake-Haxe#2]
i open "ShockwaveParser.hxproj" and i select target build to "Earthquake" and i click on "test project" to build it.
it give me this
"
Building ShockwaveParser
Running Pre-Build Command Line...
cmd: haxe modules.hxml Earthquake.hxml
Exception: The system cannot find the file specified
Done(1) "
sorry my English bad

**Comment by Mohamed-moneim-said** [comment]
i use flash develop

**Comment by Brian151** [comment]
if i were to be completely honest with you, i do not like build scripts. especially using them for things which the tools should automatically cover...

my current [re-]build lacks this problem because i gave-up on the module-based design. it has advantages, but it's difficult to compile properly... 
my logic was basically this: 
module riff : this decodes the RIFF/RIFX chunk-container format, the format is used in other places besides director/shockwave
module earthquake : decodes director/shockwave movies/casts
aftershock/application : as earthquake module is purely a library, it does NOTHING unless external code tells it to

flash develop and the haxe compiler like to create code that isn't exposed to the global scope:
```js
(function test(x,y){})();
```
probably because this is a "proper" javascript convention. but it doesn't work for re-usable libraries. all those common JS frameworks do this, instead:
```js
(function(glob) {
function test(){}
glob.test = test;
})(this);
```


anyways...
based on that error, the hxml files are not located?
that error report doesn't give me much to work with, something compilers are famous for

**Comment by Mohamed-moneim-said** [comment]
That's mean i can't fix this error and build it :-(

**Comment by Brian151** [comment]
you cloned the entire repository, right?

**Comment by Mohamed-moneim-said** [comment]
yes

**Comment by Mohamed-moneim-said** [comment]
you can help me in build??

**Comment by Brian151** [comment]
i can try, but it's difficult without descriptive error reports...

**Comment by Mohamed-moneim-said** [comment]
screen shoot
![error](https://user-images.githubusercontent.com/55868763/96974678-da8d6f80-1519-11eb-8d5e-35244beff942.png)

**Comment by Mohamed-moneim-said** [comment]
and if you can't fix it you can give me files after build

**Comment by Brian151** [comment]
is Haxe installed, even?

**Comment by Mohamed-moneim-said** [comment]
Haxe now built in flash develop

**Comment by Mohamed-moneim-said** [comment]
and please you can build it and give me files

**Comment by Brian151** [comment]
i really need to figure-out releases...

as it stands now, this doesn't do anything. it's lots of really ugly debugging code that brings nothing to the table except confirm or deny i'm reading these files correctly in the first place. if it actually were reading/displaying resources, i'd think about this...

my only real guess what's going on is that a path variable is miss-configured
something windows is known to do to some unlucky people
try opening the command promp and enter haxe

you should get something like this:

**Comment by Brian151** [comment]
and apparently now i can't upload files?!

**Comment by Mohamed-moneim-said** [comment]
why you can't upload files after build

**Comment by Mohamed-moneim-said** [comment]
please upload it, you will save my time

**Comment by Mohamed-moneim-said** [comment]
after use flash develop 5.2.0.3 error fixed but.... give me this error

"Running process: D:\Downloads\FlashDevelop-5.2.0\Tools\fdbuild\fdbuild.exe "D:\Downloads\EarthQuake-Haxe-master\EarthQuake-Haxe-master\OLD_BUILDS\haxe\ShockwaveParser.hxproj" -ipc e940bddc-6b31-4ced-a3c7-44ea06dbb7fd -version "4.1.0" -compiler "C:\HaxeToolkit\haxe" -notrace -library "D:\Downloads\FlashDevelop-5.2.0\Library" -target "Earthquake"
Building ShockwaveParser
Running Pre-Build Command Line...
cmd: haxe modules.hxml Earthquake.hxml
Invalid commandline class : earthquake.castlib.Cast should be brian151.earthquake.castlib.Cast
Invalid commandline class : earthquake.castlib.CastMember should be brian151.earthquake.castlib.CastMember
src/earthquake/Movie.hx:45: characters 26-37 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/earthquake/Movie.hx:73: characters 32-40 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/File.hx:36: characters 19-27 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/File.hx:37: characters 30-41 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/earthquake/containers/ContainerProtected.hx:16: characters 26-37 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/earthquake/containers/Container.hx:38: characters 24-35 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/earthquake/containers/Container.hx:39: characters 20-31 : Warning : This typedef is deprecated in favor of js.lib.Uint32Array
src/earthquake/containers/Container.hx:40: characters 20-31 : Warning : This typedef is deprecated in favor of js.lib.Uint32Array
src/earthquake/containers/Container.hx:46: characters 26-37 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/riff/Section.hx:36: characters 19-27 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/Section.hx:39: characters 26-37 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/riff/Section.hx:57: characters 29-37 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/LinkedSectionHandler.hx:31: characters 19-27 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/earthquake/containers/ContainerCompressed.hx:33: characters 26-37 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/riff/File.hx:38: characters 14-22 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/Section.hx:40: characters 17-28 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/riff/Section.hx:41: characters 16-24 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/Section.hx:41: characters 31-39 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/Section.hx:42: characters 14-22 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/riff/Section.hx:72: characters 16-26 : Warning : This typedef is deprecated in favor of js.lib.RangeError
src/earthquake/containers/Container.hx:76: characters 23-31 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/earthquake/containers/Container.hx:85: characters 16-24 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/earthquake/containers/Container.hx:105: characters 21-32 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/earthquake/containers/Container.hx:106: characters 22-30 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/earthquake/containers/Container.hx:128: characters 21-32 : Warning : This typedef is deprecated in favor of js.lib.ArrayBuffer
src/earthquake/containers/Container.hx:129: characters 22-30 : Warning : This typedef is deprecated in favor of js.lib.DataView
src/earthquake/Movie.hx:47: characters 20-28 : Warning : This typedef is deprecated in favor of js.lib.DataView
Build halted with errors.
Done(1)" 

you can help???

**Comment by Mohamed-moneim-said** [comment]
it say for me "Build succeeded" but were is files???

**Comment by Brian151** [comment]
most of these errors are due to JS typed arrays. for example, i had used js.html.ArrayBuffer, now it wants js.lib.ArrayBuffer
change the imports

pretty sure my current versions of Haxe and FlashDevelop are outdated

the others are an issue with my own package names...
the buildscripts (.hxml) still point to earthquake as the root package, and i re-factored that to brian151 since it's my code

**Comment by Brian151** [comment]
i would save no one's time uploading the finished builds. they're for an older version, which doesn't do anything useful.

if you were to buy a watch from me, would you want me to sell you a few prototypes of the inner workings and a handful of spare parts? prototypes btw that are so early in development you couldn't build a complete watch if you tried?

all this library can do right now is tell me whether or not it is reading the file structure correctly in the first place.
it's hard-coded to load a specific file, and it's currently only reading the individual sections and spitting their raw contents to the console

the finished builds don't offer anything, and you wouldn't save much time when you ultimately still need to re-build them to do anything else besides their current functionality

fixing the compiler errors would save more time, but not for an older version that is no longer in active development

there are three sub-folders/sub-directories:
OLD_BUILDS (abandoned, depreciated, not supported, use at own risk)
src (current, actively developed when i have time/energy)
Lists (can basically ignore, it may or may not come into play later)

try using src/haxe, and if THAT fails, open a new issue
according to your file path, that would be:
D:\Downloads\EarthQuake-Haxe-master\EarthQuake-Haxe-master\src\haxe\EarthQuake.hxproj
